version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: lagdmitrii/foodgram_backend:latest # файл с dockerhub
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: lagdmitrii/foodgram_frontend:latest # файл с dockerhub
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: lagdmitrii/foodgram_gateway:latest # файл с dockerhub
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80 # порт проверить по главному nginx
    volumes:
      - static:/static
      - media:/media